package robogp.Training;

import robogp.robodrome.view.RobodromeView;

/**
 *
 * @author Matteo Di Lucchio <matteo.dilucchio@edu.unito.it>
 */
public class TrainingGui extends javax.swing.JFrame {

    /**
     * Creates new form TrainingGui
     */
    public TrainingGui(RobodromeView robodromo){
        initComponents();
        this.setTabellone(robodromo);
        this.pack();
    }
    
    protected void setTabellone(RobodromeView robodromo){
        this.containerTabellone.add(robodromo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerTabellone = new javax.swing.JPanel();
        containerOpzioni = new javax.swing.JPanel();
        containerProgramma = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        programma = new javax.swing.JList<>();
        containerComandi = new javax.swing.JPanel();
        btnBackward = new javax.swing.JButton();
        btnPlayPause = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(1080, 370));
        setResizable(false);

        containerTabellone.setBackground(new java.awt.Color(255, 255, 255));
        containerTabellone.setForeground(new java.awt.Color(255, 255, 255));
        containerTabellone.setName("containerTabellone"); // NOI18N
        containerTabellone.setRequestFocusEnabled(false);
        containerTabellone.setLayout(new java.awt.GridLayout());
        getContentPane().add(containerTabellone, java.awt.BorderLayout.CENTER);

        containerOpzioni.setBackground(new java.awt.Color(255, 255, 255));
        containerOpzioni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        containerOpzioni.setMinimumSize(new java.awt.Dimension(300, 12));
        containerOpzioni.setName("containerOpzioni"); // NOI18N
        containerOpzioni.setLayout(new java.awt.BorderLayout());

        containerProgramma.setBackground(new java.awt.Color(255, 255, 255));
        containerProgramma.setBorder(javax.swing.BorderFactory.createTitledBorder("Istruzioni"));
        containerProgramma.setMinimumSize(new java.awt.Dimension(200, 12));
        containerProgramma.setName("containerProgramma"); // NOI18N

        programma.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "istruzione 1", "istruzione 2", "istruzione 3", "istruzione 4", "istruzione 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(programma);

        javax.swing.GroupLayout containerProgrammaLayout = new javax.swing.GroupLayout(containerProgramma);
        containerProgramma.setLayout(containerProgrammaLayout);
        containerProgrammaLayout.setHorizontalGroup(
            containerProgrammaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        containerProgrammaLayout.setVerticalGroup(
            containerProgrammaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        containerOpzioni.add(containerProgramma, java.awt.BorderLayout.CENTER);

        containerComandi.setBackground(new java.awt.Color(255, 255, 255));
        containerComandi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        containerComandi.setName("containerComandi"); // NOI18N
        containerComandi.setLayout(new java.awt.GridLayout());

        btnBackward.setText("⏮");
        btnBackward.setToolTipText("go backward");
        containerComandi.add(btnBackward);

        btnPlayPause.setText("▶⏸");
        btnPlayPause.setToolTipText("play / pause");
        btnPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPauseActionPerformed(evt);
            }
        });
        containerComandi.add(btnPlayPause);

        btnStop.setText("⏹");
        btnStop.setToolTipText("stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        containerComandi.add(btnStop);

        containerOpzioni.add(containerComandi, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(containerOpzioni, java.awt.BorderLayout.LINE_START);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("CIAO CAZZOOOOO oasidhfpaosdhf;a ausjdbnfpajnsd;fj paosdnbfghpa;jsdnhfg;ajlndf;agjnd;klfjn;asdjnf;jand");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayPauseActionPerformed

    
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TrainingGui().setVisible(true);
//            }
//        });
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackward;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnStop;
    protected javax.swing.JPanel containerComandi;
    protected javax.swing.JPanel containerOpzioni;
    protected javax.swing.JPanel containerProgramma;
    protected javax.swing.JPanel containerTabellone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    protected javax.swing.JList<String> programma;
    // End of variables declaration//GEN-END:variables
}
