package robogp.deck;

import javax.swing.ImageIcon;

/**
 *
 * @author Matteo Di Lucchio <matteo.dilucchio@edu.unito.it>
 */
public class InstructionCardGui extends javax.swing.JPanel {

    /**
     * Creates new form InstructionCardGui
     */
    public InstructionCardGui(InstructionCard sorgente) {
        //crea la gui usando la scheda istruzione
        initComponents();
        //labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(sorgente.getPath_icona())));
        ImageIcon image = new ImageIcon(getClass().getResource("./icons/card-turnR.png"));
        //labelIcon.setIcon(image);
        labelPriorita.setText("" + sorgente.getPriorita());
        labelTipoCarta.setText(sorgente.getTipo());
    }
    
    
    @Override
    public String toString(){
        String s = "";
        s += "[CardGui"
                + " " + this.labelTipoCarta.getText()
                + " " + this.labelPriorita.getText()
                + "]";
        return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPriorita = new javax.swing.JPanel();
        labelPriorita = new javax.swing.JLabel();
        panelTipoCarta = new javax.swing.JPanel();
        labelTipoCarta = new javax.swing.JLabel();
        panelIcon = new javax.swing.JPanel();
        labelIcon = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        labelPriorita.setText("priorita'");

        javax.swing.GroupLayout panelPrioritaLayout = new javax.swing.GroupLayout(panelPriorita);
        panelPriorita.setLayout(panelPrioritaLayout);
        panelPrioritaLayout.setHorizontalGroup(
            panelPrioritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrioritaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelPriorita)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPrioritaLayout.setVerticalGroup(
            panelPrioritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrioritaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelPriorita)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(panelPriorita, java.awt.BorderLayout.SOUTH);

        labelTipoCarta.setText("tipo carta");

        javax.swing.GroupLayout panelTipoCartaLayout = new javax.swing.GroupLayout(panelTipoCarta);
        panelTipoCarta.setLayout(panelTipoCartaLayout);
        panelTipoCartaLayout.setHorizontalGroup(
            panelTipoCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoCartaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelTipoCarta)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelTipoCartaLayout.setVerticalGroup(
            panelTipoCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoCartaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelTipoCarta)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(panelTipoCarta, java.awt.BorderLayout.CENTER);

        labelIcon.setText("immagine");

        javax.swing.GroupLayout panelIconLayout = new javax.swing.GroupLayout(panelIcon);
        panelIcon.setLayout(panelIconLayout);
        panelIconLayout.setHorizontalGroup(
            panelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(panelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelIconLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelIcon)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelIconLayout.setVerticalGroup(
            panelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(panelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelIconLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelIcon)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(panelIcon, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelPriorita;
    private javax.swing.JLabel labelTipoCarta;
    private javax.swing.JPanel panelIcon;
    private javax.swing.JPanel panelPriorita;
    private javax.swing.JPanel panelTipoCarta;
    // End of variables declaration//GEN-END:variables
}
